# Generated by Django 5.1.2 on 2024-10-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_name_alter_product_created_at_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='bane',
            new_name='name',
        ),
    ]
